name: aro-ci-cd

env:
  REGISTRY: docker.io/cloudattech
  REGISTRY_USER: cloudattech
  REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "amol-tapase-dev"
  APP_NAME: "django-example-app"
  TAG: "latest"

on: [ workflow_dispatch]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout Sourcecode
          uses: actions/checkout@v3

        - name: Build from Dockerfile
          id: image-build
          uses: redhat-actions/buildah-build@v2
          with:
           image: ${{ env.APP_NAME }}
           tags: ${{ env.TAG }}
           dockerfiles: |
            ./Dockerfile

        - name: Push to registry
          id: push-to-registry
          uses: redhat-actions/push-to-registry@v2
          with:
           image: ${{ steps.image-build.outputs.image }}
           tags: ${{ steps.image-build.outputs.tags }}
           registry: ${{ env.REGISTRY }}
           username: ${{ env.REGISTRY_USER }}
           password: ${{ env.REGISTRY_PASSWORD }}
  Deploy:      
    name: Deploy
    runs-on: ubuntu-20.04
    needs: [ Build ]
    steps:
        - name: Checkout Sourcecode
          uses: actions/checkout@v3

        - name: Login to ARO Cluster
          id: set-aro-context
          uses: redhat-actions/oc-login@v1
          with:
            openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
            openshift_token: ${{ env.OPENSHIFT_TOKEN }}
            insecure_skip_tls_verify: true
            namespace: ${{ env.OPENSHIFT_NAMESPACE }}

        - name: Create and expose app
          id: deploy-app
          uses: Azure/k8s-deploy@v4
          with:
            namespace: ${{ env.OPENSHIFT_NAMESPACE }}
            manifests: |
              manifest/deployment.yml
            images: |
              ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.APP_NAME }}:${{ env.TAG }}


